### ISSUE TITLE
Segmentation fault/ maybe

### ISSUE THREAD

**Issue by Exarkuniv** [OpenDUNE/OpenDUNE#363] opened 2021-11-08 21:30 UTC
i have compiled this for my Pi4 running Retropie. Buster 10. 
the game starts and shows the intro, but then crashes before the menu comes up
when i run ./opendune thiis the last line that comes up when it crashes 

```
GameLoop_PlayAnimation() 16 INTRO7b  mode=2 flags=000
INTRO7b.WSA : 22 304x120 9360 0
               00000000 006a0000
Dirty area : (8,24)-(312,144)
Segmentation fault
````

looking around i found a issue with something with Segmentation fault. so i did what was said in it.

i did check the sha and it matches what was in this [issue ](https://github.com/OpenDUNE/OpenDUNE/issues/358#issue-855537917)

`./configure --enable-debug=3` then `make` then `make run-gdb`

here is what my ./configure --enable-debug=3 says
```
checking awk... awk
detecting OS... UNIX
checking build system type... arm-linux-gnueabihf
checking host system type... arm-linux-gnueabihf
checking universal build... no
checking build cc... gcc
checking host cc... gcc
checking strip... disabled
checking builtin depend... yes
checking makedepend... disabled
detecting cpu-type... 32 bits
checking static... no
using debug level... level 3
using link time optimization... no
checking OSX sysroot... not OSX, skipping
checking SDL2... found version 2.0.10
checking SDL2_image... found version 2.0.4
checking SDL... disabled
checking asound... found
checking oss... not found
checking pulse... found
checking kai... not found
checking munt... not found
checking GDI video driver... not Windows, skipping
checking assert... enabled
checking sort... sort
checking stripping... skipped
checking distcc... no (only used when forced)
checking ccache... no (only used when forced)
checking revision... git detection
installation directory... /
using CFLAGS_BUILD...  -fno-common -Wall -Wsign-compare -Wundef -Wwrite-strings -Wpointer-arith -W -Wredundant-decls -Wformat=2 -Wformat-security -Wno-format-nonliteral -Winit-self -fno-strict-aliasing -Wcast-qual -fno-strict-overflow -Wno-free-nonheap-object -rdynamic
using LDFLAGS_BUILD...  -rdynamic
using CFLAGS...  -mcpu=cortex-a72  -mfpu=neon-fp-armv8 -O2 -fno-common -Wall -Wsign-compare -Wundef -Wwrite-strings -Wpointer-arith -W -Wredundant-decls -Wformat=2 -Wformat-security -Wno-format-nonliteral -Winit-self -fno-strict-aliasing -Wcast-qual -fno-strict-overflow -Wno-free-nonheap-object -rdynamic -DUNIX -I/home/pi/RetroPie-Setup/tmp/build/opendune/include -g -D_DEBUG -fno-inline -O0 -DWITH_SDL2 -I/usr/include/SDL2 -D_REENTRANT -DSDL_FORCE_INLINE='static __inline' -DALSA -D_REENTRANT -DPULSEAUDIO
using LDFLAGS...  -L/usr/lib/arm-linux-gnueabihf -lSDL2 -lSDL2_image -lasound -lpulse  -rdynamic
Generating Makefile...
Generating objs/Makefile...
make[1]: Entering directory '/home/pi/RetroPie-Setup/tmp/build/opendune/objs/debug'
```

when i run make run-gdb

i get this
```
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./opendune...done.
Starting program: /home/pi/RetroPie-Setup/tmp/build/opendune/bin/opendune
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
opendune.ini file not found.
Globals :
  g_dune2_enhanced = 1
  g_debugGame = 0
  g_debugScenario = 0
  g_debugSkipDialogs = 0
  s_enableLog = 0
  g_starPortEnforceUnitLimit = 0
fopendatadir(3, dune.cfg, rb)
DSP_Init() PulseAudio version 12.2.0
PulseAudio pa_context_connect() failed
fopendatadir(1, INTRO.PAK, rb)
fopendatadir(1, DUNE.PAK, rb)
```

the make run-gdb does not seem to end. it just sits there. i had it running for over a hour, unless it does take that long

when i get time i will try the backtrace

**Comment by miniupnp** [comment] 2021-11-09 21:38
when you are in gdb you can hit CTRL-C and show the backtrace

**Comment by miniupnp** [comment] 2021-11-10 10:49
@Exarkuniv Have you tried with the latest master ? I recently added code to support Data file from DUNE2 V1.0.

in anycase, can you check which version of Dune2 files you are using ?
* Dune2 v1.7 :
  * DUNE.PAK 408048 bytes
  * DUNE2.EXE 371616 bytes
* Dune2 v1.0 :
  * DUNE.PAK 438114 bytes
  * DUNE2.EXE 365504 bytes

**Comment by Exarkuniv** [comment] 2021-11-10 15:12
i am running v1.07 per `strings DUNE2.EXE | grep V1\\.`
here is my backtrace
```
(gdb) bt
#0  __GI__dl_debug_state () at dl-debug.c:74
#1  0xb6fd4110 in _dl_map_object_from_fd (
    name=name@entry=0xb6f79a54 "libXrandr.so.2", origname=origname@entry=0x0,
    fd=8, fbp=fbp@entry=0xbeffecf4,
    realname=0x166080 "/usr/lib/arm-linux-gnueabihf/libXrandr.so.2",
    loader=loader@entry=0x0, l_type=2, l_type@entry=-1090523920,
    mode=-1879048190, mode@entry=-1090523284, stack_endp=0xbeffecf0,
    stack_endp@entry=0xbeffece8, nsid=nsid@entry=0) at dl-load.c:993
#2  0xb6fd6d78 in _dl_map_object (loader=0x0, loader@entry=0xb6ff9508,
    name=name@entry=0xb6f79a54 "libXrandr.so.2", type=type@entry=2,
    trace_mode=trace_mode@entry=0, mode=mode@entry=-1879048190, nsid=0)
    at dl-load.c:2248
#3  0xb6fe20e4 in dl_open_worker (a=0xbefff140) at dl-open.c:228
#4  0xb6cde4f8 in __GI__dl_catch_exception (exception=0xbefff1b8,
    operate=0xb6d13000, args=0xbefff134) at dl-error-skeleton.c:196
#5  0xb6fe1c2c in _dl_open (file=0xb6f79a54 "libXrandr.so.2",
    mode=-2147483646, caller_dlopen=0xb6f389f0, nsid=-2, argc=1,
    argv=0xbefff624, env=0xbefff62c) at dl-open.c:599
#6  0xb6b34bd4 in dlopen_doit (a=0xbefff3a4) at dlopen.c:66
#7  0xb6cde4f8 in __GI__dl_catch_exception (exception=0x0,
    exception@entry=0xbefff358, operate=0xb6d13000, args=0xbefff358,
    args@entry=0xbefff3a4) at dl-error-skeleton.c:196
#8  0xb6cde5b8 in __GI__dl_catch_error (objname=0x1406f4, errstring=0x1406f8,
--Type <RET> for more, q to quit, c to continue without paging--
--Type <RET> for more, q to quit, c to continue without paging--ret
    mallocedp=0x1406f0, operate=<optimized out>, args=0xbefff3a4)
    at dl-error-skeleton.c:215
#9  0xb6b3545c in _dlerror_run (operate=0xb6b34b58 <dlopen_doit>,
    args=0xbefff3a4, args@entry=0xbefff39c) at dlerror.c:163
#10 0xb6b34c90 in __dlopen (file=0xb6f79a54 "libXrandr.so.2",
    mode=<optimized out>) at dlopen.c:87
#11 0xb6f389f0 in ?? () from /usr/lib/arm-linux-gnueabihf/libSDL2-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by miniupnp** [comment] 2021-11-10 16:20
that is strange, it looks like it is stuck in libSDL2...
maybe you are looking at the wrong thread. try to switch
```
(gdb) info threads
  Id   Target Id                                    Frame 
* 1    LWP 100846 of process 13691                  0x0000000800f26d4a in _sigsuspend () from /lib/libc.so.7
  2    LWP 101272 of process 13691 "opendun:disk$0" 0x00000008011ff68c in ?? () from /lib/libthr.so.3
  3    LWP 101274 of process 13691 "opendun:disk$1" 0x00000008011ff68c in ?? () from /lib/libthr.so.3
  4    LWP 101275 of process 13691 "opendun:disk$2" 0x00000008011ff68c in ?? () from /lib/libthr.so.3
  5    LWP 101276 of process 13691 "opendun:disk$3" 0x00000008011ff68c in ?? () from /lib/libthr.so.3
(gdb) thread 2
[Switching to thread 2 (LWP 101272 of process 13691)]
#0  0x00000008011ff68c in ?? () from /lib/libthr.so.3
(gdb) bt
#0  0x00000008011ff68c in ?? () from /lib/libthr.so.3
#1  0x00000008011f2eb0 in ?? () from /lib/libthr.so.3
#2  0x00000008011fccab in ?? () from /lib/libthr.so.3
#3  0x0000000802f18fbc in ?? () from /usr/local/lib/dri/i965_dri.so
#4  0x0000000802f190b9 in ?? () from /usr/local/lib/dri/i965_dri.so
#5  0x00000008011f0fac in ?? () from /lib/libthr.so.3
#6  0x0000000000000000 in ?? ()
```

**Comment by miniupnp** [comment] 2021-11-10 16:39
your issue may be related to #362

**Comment by Exarkuniv** [comment] 2021-11-10 16:41
it might be. i did see that, but since mine was happening at the into is why i made a new issue.

i am watching his too to see what happens on his

**Comment by Exarkuniv** [comment] 2021-11-10 16:56
i did info threads 
```
(gdb) info threads
  Id   Target Id                              Frame
* 1    Thread 0xb60e7040 (LWP 826) "opendune" __GI__dl_debug_state ()
    at dl-debug.c:74
```

**Comment by miniupnp** [comment] 2021-11-10 17:58
It may be a memory corruption error :(

**Comment by Exarkuniv** [comment] 2021-11-10 18:07
hmm

ill try a new SD card and a clean load. i will report back

**Comment by miniupnp** [comment] 2021-11-10 18:15
> hmm
> 
> ill try a new SD card and a clean load. i will report back

I mean elsewhere in OpenDune code

**Comment by Exarkuniv** [comment] 2021-11-10 19:45
ahh
well with everthing that i have done on the sd and image i wanted to make sure.
but sadly it is the same outcome as before

**Comment by miniupnp** [comment] 2021-11-17 10:52
I think I have found that the issue is from commit 5a912ffee9fc6101cd8f13be90c4b227057dc846
I have to understand what happens when the .WSA has no first frame, which seems to be the case for INTRO7b.WSA.

@Exarkuniv can you try to build 054cce6948131aac33f948f7c9cf08185cbb72f0
```
git checkout 054cce6948131aac33f948f7c9cf08185cbb72f0
./configure  --enable-debug=1 && gmake run-gdb
```

**Comment by miniupnp** [comment] 2021-11-17 10:55
I close this one as #362 was reported earlier

**Closed by miniupnp** 2021-11-17 10:55 UTC
Labels: bug, duplicate
